### PR TITLE
chore: add documentation to all the locator annotation and InitializableDependency

### PR DESCRIPTION
**Pull request by eb-so**
add documentation to all the locator annotation and `InitializableDependency`.

### CODE REVIEW

**Comment by eb-so** [comment]
fixes https://github.com/Stacked-Org/stacked/issues/984

**Comment by eb-so** [comment]
@ferrarafer Please review

**Review by ferrarafer — APPROVED** [review]
Awesomeee 🔥 !! Thanks for the collaboration ❤️

**Pull request merged**
